### ISSUE TITLE
setting resetInitialPos does not work // or I don't understand

### ISSUE THREAD

**Issue by Zeitvertreib** [IsraelZablianov/draggable-vue-directive#22]
I want a thing to return to its initial Position, as long as it has not been dragged out of a certain boundry/ threshold. ..but first things first, I want to have it always return, so I do this in my .vue:
```
  ...
  <div v-draggable="draggableValue">
    test
  </div>
  ...
  import { Draggable } from 'draggable-vue-directive'
  ...
  export default {
        directives: {
            Draggable,
        },
        data() {
            return {
                draggableValue: {
                    resetInitialPos: true
                };
            }
        }
```
but that doesn't do a thing.

What am I missing here or is it a bug?

regards

**Comment by IsraelZablianov** [comment]
You miss understood, you should use toggle resetInitialPos when needed, meaning: after some action you should toggle resetInitialPos to true and than back again to false.

e.g.
``` js
    onReset() {
        this.draggableWithResetPosition.resetInitialPos = true;
        setTimeout(() => {
            this.draggableWithResetPosition.resetInitialPos = false;
        }, 0);
    }
```

please look at the [draggable demo app](https://github.com/IsraelZablianov/draggable-demo) for more samples regarding the draggable directive.

for stopping the draggable from moving you have the property stopDragging

**Comment by Zeitvertreib** [comment]
yes yes, awesome, and your repo does save me a lot of work, so I am very thankful!
But ```resetInitialPos``` is listed in the readme under:
"The object passed to the directive is called the directive value.
For example in v-draggable="draggableValue" draggableValue can be an object containing the folowing fields:  ..."

So I thought I can use it like the other fields.

**Comment by IsraelZablianov** [comment]
You are using it like other fields, but you are right, it might be a bit confusing because once you set the `resetInitialPos` the draggable object is reset to it's initial position immediately and the tricky part is, if you won't toggle the the value again, in the next directive value update (say you update the draggable handler or whatever) the draggable object will be reseted again.
The conclusion here is that the `resetInitialPos ` is valid and will take place immediately and only one time, when it's value set to true.
Hope it make sense to you, if not U may suggest other/additional behaviour that U would like to see.

Israel

**Comment by IsraelZablianov** [comment]
In your case you won't see any change because as I said before the reset initial position should be triggered  later in the app life time.
It make no sense to set `resetInitialPos: true` in the beginning because it is already in it's initial position, so if you set  `resetInitialPos: true`  in the beginning before the initialPos changed you did nothing.

Did you looked at the demo app I sent you before? please look, there is a working sample.
